[global]
    update every = 5
    memory mode = dbengine

[db]
    mode = dbengine
    storage tiers = 1
    dbengine tier 0 retention size = 0
    dbengine tier 0 retention time = 7d

[ml]
    enabled = no

[web]
    bind to = 127.0.0.1

[plugins]
    apps = no
    ebpf = no
